### ISSUE TITLE
Procedural Generation

### ISSUE THREAD

**Issue by orion42m** [gregkwaste/NMSMV#2]
Hello,
I saw that procedural model generation is currently broken and is pending repair. Do you have an estimate for when it will be fixed?

**Comment by gregkwaste** [comment]
Hi there,

I'm afraid I can't give you an estimate :( 
The thing that I focus on regarding proc generation is procedural texture generation that I'm trying to improve so that it generates more "correct" results.

**Comment by gregkwaste** [comment]
Will close this issue for now. Proc gen updates are not in the near planning horizon :(
