### ISSUE TITLE
Instant freeze on startup

### ISSUE THREAD

**Issue by ElBretzelito** [gregkwaste/NMSMV#3]
Hi
I tried every version, but they all do the same thing. I get the "Do you have unpacked game files?"  window, but it doesn't matter what I answer. After that I can only see the black background of the mv appearing, the white areas around it where features should appear, but nothing loads, the program just freezes. If I wait long enough, I'll finally have the "NMSMV Has stopped working". 
Same computer as I play nms on, so I assume it's more than strong enough for a mv.
I'm on windows 10

The only videos I could find about your model viewer were DaveUK's , and it seems like most people in the comments were running it with no issue. But I've seen two comments talking having similar probems to mine, and nobody seems  to have found a solution.

**Comment by jackcarey** [comment]
I'm running into a similar issue with 0.90.7-hotfix on Windows 11. A blank white window loads, CPU & RAM get very high, then nothing happens no matter how long I leave it.

**Comment by gregkwaste** [comment]
Sorry for the late reply
@ElBretzelito, @jackcarey  you can attach your log.out files just to see if the app indeed hung at some point.

At startup, after the app identifies the NMS installation directory, it tries to cache the contents of all the .pak files of the game. That may cause the app to hang but in reality it works on the pak files in the background.

Also I highly recommend you get the new version 0.91.1 which has received a lot of upgrades (moved to NET 6.0) with regards to rendering performance and some bug fixes related to other crashes. 

Note that the new version is trying to work on the PAK files asynchronously so it should not cause any hangs (theoretically). In my case, with the game installed on an SSD this doesn't take more than 3-4 seconds for the process to finish.

**Comment by gregkwaste** [comment]
> Hi there, thank you for the detailed report. Apparently the log.out was enough to figure out the issue XD

Rhetorical question @TalonGrayson, are you using an AMD graphics card?

**Comment by TalonGrayson** [comment]
> Apparently the log.out was enough to figure out the issue XD

Ha, oh well, better to have too much info than too little I guess!

> Rhetorical question @TalonGrayson, are you using an AMD graphics card?

Yeah, I am...

**Comment by gregkwaste** [comment]
> 
Open Bound_FS.glsl and delete line 10 : uniform vec3 color;

Restart the app.

**Comment by gregkwaste** [comment]
> > Apparently the log.out was enough to figure out the issue XD
> 
> Ha, oh well, better to have too much info than too little I guess!
> 
> > Rhetorical question @TalonGrayson, are you using an AMD graphics card?
> 
> Yeah, I am...

Open Bound_FS.glsl and delete line 10 : uniform vec3 color;

Restart the app.

**Comment by TalonGrayson** [comment]
That fixed it for me. Thank you very, very much!

**Comment by gregkwaste** [comment]
I'm closing this issue. If you guys @ElBretzelito , @jackcarey still got any issues please open a new ticket.
