### ISSUE TITLE
Doesn't properly exports obj file

### ISSUE THREAD

**Issue by AmazingDiamond** [gregkwaste/NMSMV#4]
I tried multiple versions, with and without updating libMBIN, and it opens and views fine, but after i save any model the file size is under 1MB and when i try opening it in Blender it shows almonst nothing - just one tringle or floating points. It's like mesh is crumbled into one plane, but even worse. 
![image](https://user-images.githubusercontent.com/61892596/222933298-f7013c87-b1a2-47ba-816a-599d3c52a200.png)

i have checked the logs, and noticed that at the very end there's "NOT IMPLEMENTED YET" which I suppose appears when it's esporting. This is confirmed by same multiple messages after repeated attempts to save in row and closing. I have watch a youtube guide which the firts version NMSMV_v0.89.4 was used, having exaple that it should work, but when i opening mbin it crashes

**Comment by gregkwaste** [comment]
Thanks for the report! It is advised to always use the latest version + the updated libmbin version just to make sure there is no inconsistency with previous versions of the game. Can you please tell me which file you tried to export so that I can take a look?

**Comment by AmazingDiamond** [comment]
literally anything i have tried: walker sentinel, the drone, some spacecraft parts. On a screenshot it's a minotaur from "robots/mech" if i recall.

**Comment by AmazingDiamond** [comment]
literally anything i have tried: walker sentinel, the drone, some spacecraft parts. 
On a screenshot it's a minotaur from "robots/mech". I must mention th
at the "NOT IMPLEMENTED YET" part is gone after reinstall it today. But still no use.
this is from that mino config and it's OBJ:
[1.zip](https://github.com/gregkwaste/NMSMV/files/11004061/1.zip)
I have opened it thought the notepad and it's look real - a giant string of coordinates, but trying to open it in blender or CAD programm makes it like nothing. Opening other OBJ files from internet work normal on my PC, so i don't even know if the problem is on my end or not.

**Comment by gregkwaste** [comment]
Thanks for the info. I'll take a closer look once I can and I will let you know. In obj files, lines that start with v are vertex coordinates, while lines that start with f are faces. In blender normally you should be able to see at least some object being imported. Even if its only vertices. But you should see at least a mesh in the scenegraph.

**Comment by pixelquarry** [comment]
Just chiming in. I ran into the same problem and replaced the libMBIN.dll with the latest version. That solved the decompile error message but did nothing for the OBJ export.

Everything looks fine in NMSMV...
![NMSMV_01](https://user-images.githubusercontent.com/130376938/230917982-e8bb8827-91ea-47c9-9af9-e88dad402f19.jpg)

...but the exported mesh looks like this. The vertex count seems unaffected though.
![NMSMV_02](https://user-images.githubusercontent.com/130376938/230917983-1e8cd9d1-37a0-43a4-be2c-181e82129ca1.jpg)

Cheers!

**Comment by gregkwaste** [comment]
Hello guys,

sorry for my late reply, I found out some time know to update the code base and deal with all the open issues. I cannot reproduce the issue with the obj export and I don't see any introduced change from 0.91.1.

I just tried exporting the astronaut model, the entire dropship_proc.scene and the walker drone as well

![image](https://github.com/gregkwaste/NMSMV/assets/7515235/6b579a53-adf7-4664-b1a6-546d7dda3e66)

![image](https://github.com/gregkwaste/NMSMV/assets/7515235/18739629-02a1-4eee-9ae2-6dd1f2cb3dbc)

![image](https://github.com/gregkwaste/NMSMV/assets/7515235/626e0e04-6a97-44a2-b566-d12fe54e4037)

Tried to import the exported obj's in Blender and the 3D Viewer and it seems to be working as intended (well the textures are not included but this is expected)

I'll push 0.91.2 in the upcoming days so please keep an eye and let me know if the issue persists. My expectation is that even with 0.91.1 obj export should work as intended.

**Comment by pixelquarry** [comment]
Hey Greg,
no worries, thanks for looking into this.

I did some testing on my own to see if the problem could be on my end. The fact that you can't reproduce the export error seems to confirm my suspicion. 

Since Steam allows downloads of older releases of games, I downloaded NMS from before v0.91.1 came out, even tired earlier releases of NMSMV. It either crashed right away or resulted in the same mesh mess.

So I guess the problem is caused on my system. Can you think of anything that might be different between our systems?
Version of NMS, NMSMV, libMBIN? I think I'm up to date on all of them. Are there any components in the export process that use system resources outside of NMSMV? Some windows libs that might be different for some reason?

I'll wait for v0.92 and hope for the best.

Cheers

**Comment by pixelquarry** [comment]
I'm at a loss...

- new PC
- new install of Steam
- new install of NMS
- new download of v0.91.1
- new install of .NET 6.0

"Do you have unpacked game files?" > no > "Open file from .pak" > export as obj > WORKS!

- new download of MBINCompiler_v4,37,0-pre1
- unpack game files

"Open file" > export as obj > Doesn't work
"Open file from .pak" > export as obj > Doesn't work (OMG, why? It's the same original game file.)
"Update libMBIN" > export as obj > Doesn't work

I have no clue what's going on :(

**Comment by pixelquarry** [comment]
Would it be possible for you to send me the entire dropship_proc.scene from your test as an obj?

**Comment by gregkwaste** [comment]
> Hey Greg, no worries, thanks for looking into this.
> 
> I did some testing on my own to see if the problem could be on my end. The fact that you can't reproduce the export error seems to confirm my suspicion.
> 
> Since Steam allows downloads of older releases of games, I downloaded NMS from before v0.91.1 came out, even tired earlier releases of NMSMV. It either crashed right away or resulted in the same mesh mess.
> 
> So I guess the problem is caused on my system. Can you think of anything that might be different between our systems? Version of NMS, NMSMV, libMBIN? I think I'm up to date on all of them. Are there any components in the export process that use system resources outside of NMSMV? Some windows libs that might be different for some reason?
> 
> I'll wait for v0.92 and hope for the best.
> 
> Cheers

Hmmm so you're trying to export from an older game version?

**Comment by pixelquarry** [comment]
> 

I tried to export from the newest version and when that didn't work I tried some older ones. Just to see if that gives me a different result.

**Comment by gregkwaste** [comment]
> > 
> 
> I tried to export from the newest version and when that didn't work I tried some older ones. Just to see if that gives me a different result.

Unfortunately since they are usually minor changes to libMBIN, the NMSMV codebase has to be updated most of the time due to these changes, so unfortunately versions are not backwards compatible. Your best bet is to always use the latest release along with the latest libMBIN either included in the release or an updated version (via the app).

I'll re-export the objs once I got some time just to make sure that it works with the version that I'm planning to release and I'll send them over.

**Comment by pixelquarry** [comment]
> 

Thank you!

**Comment by pixelquarry** [comment]
So, I've tried v0.91.2 and got the same results 😔
It has to be something on my end that messes up the exports.
If you ever get the chance to export the dropship model again, I'd appreciate a download link.

Cheers

**Comment by gregkwaste** [comment]
Sorry, for the late response, several bugs have been improved since. Re-open a new issue if problems persist
