### ISSUE TITLE
Not working after new update

### ISSUE THREAD

**Issue by GemoGens** [gregkwaste/NMSMV#8]
Launches, but then it wont open models with the following message
![Screenshot 2024-07-22 221105](https://github.com/user-attachments/assets/1b395a51-4687-4d64-b496-108aa3e7818c)

Tried updating libMBIN file from official github and from the app.
It changes the libMBIN file and the NMSMV.dll file (the size of them changes) but then i start it up and nothing happens. I can still see the app running in my task manager but there is no application to work with.

Any help would be appreciated, I would like to create a 3d ship file using the 3d models as reference for a contest.

**Comment by dailerob** [comment]
I would like to second this, having the exact same issue post 5.0.

**Comment by gregkwaste** [comment]
The viewer already had some issues with the last update prior to 5.0. However, they introduced even more changes in the geometry files as it seems with 5.0. I'm waiting for the MbinCompiler team to add full support for 5.0 and then I'll be able to work and repair the viewer. Till then, the app is indeed borked as expected :/

**Comment by gregkwaste** [comment]
Latest pre-release should support the latest update.
